# Generated by Django 5.0.1 on 2024-02-11 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxiparty",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 11, 11, 11, 33, 989242, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="taxiparty",
            name="rider",
            field=models.TextField(default="sangjun"),
        ),
        migrations.AddField(
            model_name="taxiparty",
            name="route",
            field=models.TextField(default="wa mart to pt st"),
        ),
    ]
