# Generated by Django 5.0.1 on 2024-02-11 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0002_taxiparty_date_taxiparty_rider_taxiparty_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxiparty",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 11, 11, 11, 57, 266705)
            ),
        ),
    ]
