# Generated by Django 5.0.1 on 2024-02-11 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0003_alter_taxiparty_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxiparty",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
