# Generated by Django 5.0.1 on 2024-02-16 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0010_alter_taxiparty_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxiparty",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
