# Generated by Django 5.0.1 on 2024-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0011_alter_taxiparty_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxiparty",
            name="rider",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="taxiparty",
            name="route",
            field=models.TextField(),
        ),
    ]
