# Generated by Django 5.0.1 on 2024-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0013_location_remove_taxiparty_rider_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxiparty",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taxiparty.route"
            ),
        ),
    ]
