# Generated by Django 5.0.1 on 2024-03-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0014_alter_taxiparty_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxiparty",
            name="route",
        ),
        migrations.AddField(
            model_name="taxiparty",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination",
                to="taxiparty.location",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxiparty",
            name="origin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin",
                to="taxiparty.location",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Route",
        ),
    ]
