# Generated by Django 5.0.1 on 2024-03-31 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0015_remove_taxiparty_route_taxiparty_destination_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taxiparty",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxiparty",
            name="rider",
            field=models.ManyToManyField(
                related_name="rider", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
