# Generated by Django 5.0.6 on 2024-05-25 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiparty", "0018_alter_taxiparty_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxiparty",
            name="date",
            field=models.DateField(default=datetime.date(2024, 5, 25)),
        ),
    ]
