# Generated by Django 5.0.6 on 2024-05-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.TextField(help_text="<br/>Legal Name", max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="<br/>Username used to Log-in",
                max_length=20,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
